-- Insert script for Medellín Underground Collection (34 locations)
-- Requires the 'locations' table to exist

INSERT INTO public.locations (
    city, city_slug, country, category, name, neighborhood, what_it_is, why_it_matters, instagram, website, sort_rank
) VALUES 
-- 🍸 Speakeasies & Hidden Bars
('Medellín', 'medellin', 'Colombia', 'speakeasy', 'Insólito', 'Manila', 'A high-end speakeasy hidden inside a vintage bookstore in Manila.', 'Perfectly fits the "good shit most people don''t know about" vibe. Mixologist-crafted cocktails in an intimate, literary setting.', 'https://www.instagram.com/insolito.bar', null, 1),
('Medellín', 'medellin', 'Colombia', 'speakeasy', 'La Casa de Ruby', 'Calle 10', 'A bar disguised as a normal residential house behind a Japanese ice cream shop on Calle 10.', 'True speakeasy entrance. Dim lighting, vintage decor, and experimental drinks.', 'https://www.instagram.com/lacasaderuby/', null, 2),
('Medellín', 'medellin', 'Colombia', 'speakeasy', 'Z Bar', 'El Poblado', 'A subterranean 1920s-themed jazz speakeasy.', 'Located in the basement of the Marquee Hotel. Elegant, upscale vibe, great for curated live jazz.', null, 'https://hotelelmarquee.com/dining/z-bar/', 3),
('Medellín', 'medellin', 'Colombia', 'speakeasy', 'La Oculta', 'Provenza', 'An exclusive club/bar behind an unmarked door in Provenza.', 'You mentioned no Provenza unless it''s a speakeasy. This is the definition of a stylish, unmarked-door speakeasy that locals and high-end expats frequent.', 'https://www.instagram.com/laocultamedellin/', null, 4),
('Medellín', 'medellin', 'Colombia', 'speakeasy', 'Victoria Regia', 'Milla de Oro', 'An exotic cocktail bar accessible only through a hidden door in Milla de Oro.', 'Upscale, elegant decor with luxurious ingredients. Very exclusive feel.', 'https://www.instagram.com/victoriaregiamed/', null, 5),
('Medellín', 'medellin', 'Colombia', 'speakeasy', 'Black Sheep', 'Astorga', 'A reservation-only, tiny speakeasy in Astorga.', 'Small, candlelit, and focuses heavily on curated whiskey and mezcal. Very intimate.', 'https://www.instagram.com/blacksheepmedellin', null, 6),
('Medellín', 'medellin', 'Colombia', 'speakeasy', 'Siete Pulgadas', 'Laureles', 'A tiny, laid-back listening bar in Laureles.', 'Underground feel, focuses heavily on music quality (vinyls) and craft local spirits.', 'https://www.instagram.com/sietepulgadas_bar/', null, 7),

-- 🪩 Underground Techno & Music
('Medellín', 'medellin', 'Colombia', 'techno', 'Sonorama', 'El Poblado', 'A highly respected underground techno club.', 'Constantly cited by locals as the legitimate, raw techno scene away from the reggaeton clubs.', 'https://www.instagram.com/sonoramamedellin/', null, 8),
('Medellín', 'medellin', 'Colombia', 'techno', 'Calle 9+1', 'El Poblado', 'An electronic/alternative club in El Poblado with a gritty, downtown style.', 'It has a legendary status among the alternative crowd and hosts great international/local DJs in an intimate space.', 'https://www.instagram.com/calle9mas1/', null, 9),
('Medellín', 'medellin', 'Colombia', 'music', 'Casa de la Luna', 'El Poblado', 'An alternative venue hosting drum and bass, jungle, and UK garage.', 'Moves away from the standard Medellín music scene into highly niche subgenres.', 'https://www.instagram.com/casadelalunamed', null, 10),
('Medellín', 'medellin', 'Colombia', 'music', 'La Pascasia', 'Centro', 'An independent music and cultural venue in downtown Medellín.', 'Run by a local collective (Música Corriente). It’s the beating heart of the non-commercial, authentic local art scene.', null, 'http://lapascasia.com/', 11),
('Medellín', 'medellin', 'Colombia', 'techno', 'Xeroclub', 'Medellín', 'A heavy, hard-techno focused underground club.', 'For those who want the Berlin-style, heavy late-night rave experience.', 'https://www.instagram.com/xeroclub', null, 12),

-- 🍽️ Secret & High-Quality Restaurants
('Medellín', 'medellin', 'Colombia', 'restaurants', 'Palazzetto D''Italia', 'Centro (La Candelaria)', 'An old-school Italian joint hidden on the second floor of an inconspicuous building in downtown.', 'Almost impossible to find if you don''t know it''s there. Incredible, authentic food with a secret-society feel.', null, null, 13),
('Medellín', 'medellin', 'Colombia', 'restaurants', 'Caduff Pasta Fresca', 'Laureles', 'A tiny, hole-in-the-wall homemade pasta spot in Laureles.', 'Very few reviews, but the ones that exist are obsessive about the quality. Intimate and authentic.', 'https://www.instagram.com/caduffpastafresca', null, 14),
('Medellín', 'medellin', 'Colombia', 'restaurants', 'La Casa del Alimento', 'Medellín', '"Author''s cuisine" served out of a transformed residential house.', 'Monthly changing menu, hyper-local ingredients. Feels like eating at a private dinner party.', 'https://www.instagram.com/lacasadelalimento', null, 15),
('Medellín', 'medellin', 'Colombia', 'restaurants', 'Alambique', 'El Poblado', 'A Colombian fusion restaurant with a completely hidden, unmarked entrance leading up a set of stairs.', 'Even though it''s gaining popularity, the hidden entrance and eclectic, rustic-chic interior make it a must-have for an "underground but premium" list.', 'https://www.instagram.com/alambiquemedellin', null, 16),
('Medellín', 'medellin', 'Colombia', 'restaurants', 'La Chagra (Jakub Gastropub)', 'El Poblado', 'A restaurant entirely dedicated to Amazonian cuisine and indigenous ingredients.', 'Extremely niche, high-concept, and provides flavors (like Mojojoy) that you simply cannot get anywhere else in the city.', 'https://www.instagram.com/lachagra', null, 17),
('Medellín', 'medellin', 'Colombia', 'restaurants', 'Hidden Bakery near Las Bastillas', 'Centro', 'A completely unnamed, local-known-only bakery near the Las Bastillas building packed with books.', 'The ultimate "if you know, you know" breakfast spot.', null, null, 18),

-- 💻 Hidden Cafes (Great for Working)
('Medellín', 'medellin', 'Colombia', 'workspaces', 'Pergamino (Oviedo Mall)', 'El Poblado (Oviedo)', 'A specific, quiet branch of the famous Pergamino cafe line.', 'The Oviedo location has a hidden second floor that is dead-quiet and perfect for deep work.', null, 'https://co.pergamino.co/', 19),
('Medellín', 'medellin', 'Colombia', 'workspaces', 'Campesino', 'El Poblado', 'A cafe with an in-house roaster, plugs everywhere, and blazing fast wifi.', 'Built specifically for people who want to hunker down and work all day. Extremely comfortable.', 'https://www.instagram.com/campesinocoffee', null, 20),
('Medellín', 'medellin', 'Colombia', 'workspaces', 'Yellow House', 'El Poblado', 'A cafe located just outside the noise of Provenza.', 'Known in expat circles for having the absolute fastest, most stable Wi-Fi in Medellín. Closes early, but unbeatable for Zoom calls.', 'https://www.instagram.com/yellowhousehostel', null, 21),
('Medellín', 'medellin', 'Colombia', 'workspaces', 'The Art Cafe', 'El Poblado', 'A secluded cafe in El Poblado.', 'Highly rated for being dead quiet, which is a rarity in Poblado.', null, null, 22),
('Medellín', 'medellin', 'Colombia', 'workspaces', 'Due Amici', 'Suramericana', 'A neighborhood coffee and pizza joint open from 10am to 11pm.', 'Great Wi-Fi, completely off the digital nomad trail, meaning it''s always easy to get a table and work in peace.', 'https://www.instagram.com/dueamicimedellin', null, 23),

-- 🎭 Unique & Off-beat Experiences
('Medellín', 'medellin', 'Colombia', 'experiences', 'Pasaje Cervantes & Torres de Bombona', 'Centro', 'A pedestrian alleyway complex in downtown Medellín filled with bohemian bars, stand-up comedy, and salsa.', 'It''s the local alternative nightlife hub. Zero tourists, 100% authentic Paisa art crowd.', null, null, 24),
('Medellín', 'medellin', 'Colombia', 'experiences', 'Aquarium Bowling Alley (Bolera Acuario)', 'Suramericana', 'A retro bowling alley in front of Luis Amigo University.', 'Requires WhatsApp reservations to get in. Very cool, old-school atmosphere completely untouched by tourism.', 'https://www.instagram.com/boleraacuario', null, 25),
('Medellín', 'medellin', 'Colombia', 'experiences', 'Game Over', 'Medellín', 'A hidden arcade restaurant where you can rent consoles, drink cocktails, and eat burgers.', 'A highly specific niche experience that serves as a great alternative to standard clubbing.', 'https://www.instagram.com/gameovermedellin', null, 26),
('Medellín', 'medellin', 'Colombia', 'experiences', 'La Mesa del Buen Comer', 'Medellín', 'An underground event combining food, language exchange, and video games.', 'Highly organic way to meet interesting locals and expats outside of the standard Tinder/bar scene.', 'https://www.instagram.com/lamesadelbuencomer', null, 27),
('Medellín', 'medellin', 'Colombia', 'music', 'Del Carajo Productions', 'Medellín', 'A promoter/venue space for heavy metal and hardcore punk in Medellín.', 'If someone wants the true, gritty, underground local experience, the Medellín punk/metal scene is historically significant and very intense.', 'https://www.instagram.com/delcarajoproducciones', null, 28),
('Medellín', 'medellin', 'Colombia', 'experiences', 'San Alejo Fair', 'Parque Bolívar', 'A massive artisan and antique market in Parque Bolívar.', 'It only happens twice a month, and is where you find the most unique, strange, and historic items from the region.', null, 'https://medellin.travel/en/san-alejo-handicraft-market/', 29),
('Medellín', 'medellin', 'Colombia', 'experiences', 'El Retiro Park (Nighttime)', 'El Retiro', 'A small town 45 minutes outside the city.', 'Instead of going to the crowded Guatapé, locals go to El Retiro at night for a peaceful, safe, and beautiful traditional town square experience.', null, null, 30),

-- 🧥 High-End Vintage & Thrift
('Medellín', 'medellin', 'Colombia', 'vintage', 'Segunda Historia', 'El Poblado', 'A curated consignment shop in Poblado focusing on high-end, bohemian, and glitzy evening wear.', 'Not a dusty thrift store; this is curated, high-quality fashion.', 'https://www.instagram.com/segundahistoriaco', null, 31),
('Medellín', 'medellin', 'Colombia', 'vintage', 'The Thrift Shop Medellín', 'Laureles', 'The leading player in the city''s thrift scene, located in Laureles.', 'Excellent curation of vintage sneakers, books, and eco-conscious clothing.', 'https://www.instagram.com/thethriftshopmedellin', null, 32),
('Medellín', 'medellin', 'Colombia', 'vintage', 'Diofill', 'Laureles', 'A vintage shop in Laureles with a very nostalgic, grandmother-inspired curation.', 'Unique, one-off heritage pieces in a highly aesthetic environment.', 'https://www.instagram.com/diofill_', null, 33),
('Medellín', 'medellin', 'Colombia', 'vintage', 'El Closet de Wendy', 'Medellín', 'A collective space selling sourced vintage clothes, jewelry, and natural products, connected to a yoga studio.', 'Great community vibe, incredibly friendly owner, very bohemian.', 'https://www.instagram.com/elclosetdewendy.vintage', null, 34)
ON CONFLICT DO NOTHING;
